### ISSUE TITLE
bug - date and time same for all contracts in respository

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#207]
date and time is shown same for all contracts in repository. even for those that were added last week or last month.

  Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - 
   
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - 419ecf97-c0ab-4007-b951-ccf95c5890fe 
      4. Balance - 1186604905 
      Detailed Message - 
       ![Alt Text](https://legalgraphaiprod.blob.core.windows.net/images/486659e158b5-4035-a4d3-2501dd801bfe1711188219816Screenshot%202024-03-23%20153222.png?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2027-01-01T15:33:17Z&st=2023-09-26T07:33:17Z&spr=https&sig=84Xh2so4BJhpHs9vwiZiBj9DR7TW7AKzOP0oLa98WeI%3D)

**Comment by rishavmitra** [comment]
**Description** - The default timestamp provided by Azure in their tables were used both for displaying date and time in the repository and the data table. So eventually when documents were analysed or last session was edited the timestamp changed in the table. Due to which the date and time were the same for all documents in the repository.
**Steps to Reproduce** - 

- Upload contracts at different time frames and analyse them.
- Return to the repository
- The date for all the documents will be same

**Expected Behavior**
- Upload contracts at different time frames and analyse them.
- Return to the repository
- The date for all the documents will be different and corresponds to the time of upload.
- The date in data table will show the date and time of the recent session data.

**Actual Behavior** 

- Upload contracts at different time frames and analyse them.
- Return to the repository
- The date for all the documents will be same
