### ISSUE TITLE
Unable to add new key legal term from the data table page.

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#306]
Unable to add new key legal term from the data table page.

Steps to replicate:
Go to data table page >> Click add key term button >> click add new key term >> add key name + questions and >> click on submit button.

After that the icon to submit key term keeps on loading.

  Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - 
   
      UserId - a835a711-7301-4d4b-81f3-1b10da74efb0 
      Detailed Message -

**Comment by Mayank-dev1822** [comment]
### RCA
The problem was with the add key-term function in the backend, as we are not self-hosting the database on our premises, and inserting the data now requires proper schemas, we didn't change the schema for the `add-key-term` function in the backend.

### Solution
I have now built proper schemas and default values for all the functions that interact with the table. This has fixed the issue. This fix has been deployed and is up for testing on `experiments.legalgraph.ai`.

## PR: https://github.com/chatcontract/django-ml-backend/pull/179
