### ISSUE TITLE
Unable to Add Files on Upload Page for Contract Analysis

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#309]
Unable to Add Files on Upload Page for Contract Analysis.

Desc: I added 10 files for upload 4 MSA and 2 DPA and 2 BAA and 2 NDA. On clicking proceed to upload i received an error on screen.

Steps to Replicate:
Go to Upload Page (Start new Analysis) >> Add Files for analysis >> Click Proceed >> confirm the files for upload >> click proceed >> Error message on Screen.

  Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - {"stack":"SyntaxError: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON","message":"Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON"}
   
      UserId - a835a711-7301-4d4b-81f3-1b10da74efb0 
      Detailed Message - {"stack":"SyntaxError: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON","message":"Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON"}

**Comment by Mayank-dev1822** [comment]
### RCA
The issue was caused by the new contract upload counter implementation. On the backend, the logic was failing to read the count from the locally stored file that is used to validate the token.

## Solution
Properly mounted the local storage in the docker file so that the container can read/write the locally stored data and validate the token.

## PR: https://github.com/chatcontract/django-ml-backend/pull/179
